# @package _global_
data:
  train_path: "/mnt/nfs/datasets/librispeech/webdataset/*train*"
  # train_path: "/dev/shm/webdataset/*train*"
  val_path: "/mnt/nfs/datasets/librispeech/webdataset/*test-clean*"
  # val_path: "/dev/shm/webdataset/*test*"
  num_workers: 15
  augmentation:
    spec_augment: True
trainer:
  max_epochs: 30
  gpus: 1
  precision: 16
  gradient_clip_val: 400  # Norm cutoff to prevent explosion of gradients
  accelerator: dp
  checkpoint_callback: True
  val_check_interval: 3000
checkpoint:
  save_top_k: 1
  monitor: "wer"
  verbose: True
  mode: "min"
